version: '3.8'

services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - type: bind
              source: .
              target: /var/www/html
        tmpfs:
            - /tmp
        depends_on:
            mysql:
                condition: service_healthy
        networks:
            - price-comparison

    nginx:
        image: nginx:alpine
        ports:
            - "8085:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - price-comparison

    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: price_comparison
            MYSQL_USER: app
            MYSQL_PASSWORD: app
        ports:
            - "3308:3306"
        volumes:
            - mysql_data:/var/lib/mysql
            - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uapp", "-papp"]
            interval: 5s
            timeout: 5s
            retries: 5
        networks:
            price-comparison:
                ipv4_address: 172.27.1.2
                aliases:
                    - db.server

    redis:
        image: "redis:6.2-alpine"
        ports:
            - "6385:6379"
        volumes:
            - redis_data:/data
        command: redis-server --appendonly yes
        networks:
            price-comparison:
                ipv4_address: 172.27.1.5

volumes:
    mysql_data:
    redis_data:

networks:
    price-comparison:
        name: price-comparison-net
        ipam:
            driver: default
            config:
                - subnet: 172.27.0.0/16
